import { Inter, Actor, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Top from "@/components/Top";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Top/>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
